name: Production deploy CRM

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TARGET_FOLDER: "/var/www/connectacrm"

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "${{ env.TARGET_FOLDER }}"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          git --work-tree="${{ env.TARGET_FOLDER }}" --git-dir="${{ env.TARGET_FOLDER }}/.git" clean -f .
          /usr/local/bin/yarn --cwd "${{ env.TARGET_FOLDER }}"
          /usr/local/bin/yarn --cwd "${{ env.TARGET_FOLDER }}" run build